### ISSUE TITLE
Build issue?

### ISSUE THREAD

**Issue by stardock** [brunocascio/nodequery-android#1]
I faced lint error when I'm trying to build the apk file, the error is:
Invalid package reference in library; not included in Android: java.nio.file. Referenced from com.fasterxml.jackson.databind.ext.PathDeserializer.
Invalid package reference in library; not included in Android: java.lang.management. Referenced from org.junit.internal.runners.statements.FailOnTimeout.
Invalid package reference in library; not included in Android: java.lang.invoke. Referenced from retrofit2.Platform.Java8.

I'm using Gradle 2.1.0 and SDK-tool v23.0.3 (android 6.0) is intalled
The apk can be generated if we ignore the error, but the application cannot be opened when I installed it on my mobile phone.
The phone I'm using is LG G3 D859 and Oppo A33m
Can you sent me the built apk file that I can have a test?

**Comment by brunocascio** [comment]
Hi @stardock,

I'm busy at the moment, but i think that your issue is related with missing dependencies. Are you using Android Studio?

If you want, send me an email with your APIKEY (because it is hardcoded: [here](https://github.com/brunocascio/nodequery-android/blob/master/app/src/main/java/com/nodequery/brunocascio/nodequery/NodeQueryService.java#L73)) and I could build and sent you.
